// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLTqG3tjv6MTQd3RZraIdJ4gv0QKNQYE8',
    appId: '1:288514665926:web:6a1cd4d06e84741ae316c7',
    messagingSenderId: '288514665926',
    projectId: 'nivio-f6110',
    authDomain: 'nivio-f6110.firebaseapp.com',
    storageBucket: 'nivio-f6110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV8q-J6A_aAklyKNuiTv4q_TiuoyO-yQI',
    appId: '1:288514665926:android:84e02eefea379d83e316c7',
    messagingSenderId: '288514665926',
    projectId: 'nivio-f6110',
    storageBucket: 'nivio-f6110.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLTqG3tjv6MTQd3RZraIdJ4gv0QKNQYE8',
    appId: '1:288514665926:web:65397d466c2710b7e316c7',
    messagingSenderId: '288514665926',
    projectId: 'nivio-f6110',
    authDomain: 'nivio-f6110.firebaseapp.com',
    storageBucket: 'nivio-f6110.firebasestorage.app',
  );
}
