// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV8q-J6A_aAklyKNuiTv4q_TiuoyO-yQI',
    appId: '1:288514665926:android:84e02eefea379d83e316c7',
    messagingSenderId: '288514665926',
    projectId: 'nivio-f6110',
    storageBucket: 'nivio-f6110.firebasestorage.app',
  );
}
