const List<Map<String, dynamic>> allProviders = [
  // User's specified top 14
  {'id': 8, 'name': 'Netflix', 'logo_path': '/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg'},
  {'id': 9, 'name': 'Amazon Prime Video', 'logo_path': '/pvske1MyAoymrs5bguRfVqYiM9a.jpg'},
  {'id': 337, 'name': 'Disney Plus', 'logo_path': '/97yvRBw1GzX7fXprcF80er19ot.jpg'},
  {'id': 350, 'name': 'Apple TV', 'logo_path': '/mcbz1LgtErU9p4UdbZ0rG6RTWHX.jpg'},
  {'id': 2, 'name': 'Apple TV Store', 'logo_path': '/SPnB1qiCkYfirS2it3hZORwGVn.jpg'},
  {'id': 283, 'name': 'Crunchyroll', 'logo_path': '/fzN5Jok5Ig1eJ7gyNGoMhnLSCfh.jpg'},
  {'id': 1899, 'name': 'HBO Max', 'logo_path': '/jbe4gVSfRlbPTdESXhEKpornsfu.jpg'},
  {'id': 15, 'name': 'Hulu', 'logo_path': '/bxBlRPEPpMVDc4jMhSrTf2339DW.jpg'},
  {'id': 2303, 'name': 'Paramount Plus Premium', 'logo_path': '/fts6X10Jn4QT0X6ac3udKEn2tJA.jpg'},
  {'id': 386, 'name': 'Peacock Premium', 'logo_path': '/2aGrp1xw3qhwCYvNGAJZPdjfeeX.jpg'},
  {'id': 309, 'name': 'Sun Nxt', 'logo_path': '/6KEQzITx2RrCAQt5Nw9WrL1OI8z.jpg'},
  {'id': 192, 'name': 'YouTube', 'logo_path': '/pTnn5JwWr4p3pG8H6VrpiQo7Vs0.jpg'},
  {'id': 188, 'name': 'YouTube Premium', 'logo_path': '/rMb93u1tBeErSYLv79zSTR07UdO.jpg'},
  {'id': 538, 'name': 'Plex', 'logo_path': '/vLZKlXUNDcZR7ilvfY9Wr9k80FZ.jpg'},
  
  // The rest
  {'id': 3, 'name': 'Google Play Movies', 'logo_path': '/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg'},
  {'id': 701, 'name': 'FilmBox+', 'logo_path': '/fbveJTcro9Xw2KuPIIoPPePHiwy.jpg'},
  {'id': 638, 'name': 'Public Domain Movies', 'logo_path': '/aN0Y2BNZQBH91JkVOeLTs8IhQrH.jpg'},
  {'id': 190, 'name': 'Curiosity Stream', 'logo_path': '/oR1aNm1Qu9jQBkW4VrGPWhqbC3P.jpg'},
  {'id': 2285, 'name': 'JustWatch TV', 'logo_path': '/g2IaWyo6jCY0rIFjb4qgZ0bSmm3.jpg'},
  {'id': 677, 'name': 'Eventive', 'logo_path': '/fwx5Ed64TkfWiRH1SOSkc4781Ts.jpg'},
  {'id': 2330, 'name': 'Jolt Film', 'logo_path': '/sBTV0rN8JUhF4G3uIceinWtQ3gi.jpg'},
  {'id': 100, 'name': 'GuideDoc', 'logo_path': '/eKVmLFHW5PeNhuR7Nedd8OIxW2M.jpg'},
  {'id': 692, 'name': 'Cultpix', 'logo_path': '/uauVx3dGWt0GICqdMCBYJObd3Mo.jpg'},
  {'id': 475, 'name': 'DOCSVILLE', 'logo_path': '/5zqbck5mo8PuVbGu2ngBUdn5Yga.jpg'},
  {'id': 175, 'name': 'Netflix Kids', 'logo_path': '/kwVegvKCinXTPuzZmYT1J3i1HJz.jpg'},
  {'id': 11, 'name': 'MUBI', 'logo_path': '/x570VpH2C9EKDf1riP83rYc5dnL.jpg'},
  {'id': 532, 'name': 'aha', 'logo_path': '/8WerMI8XcZXqPpkHTZNtzMzousF.jpg'},
  {'id': 457, 'name': 'VIX ', 'logo_path': '/jwRPknT20dfU1GeVqbcDXFyvtdG.jpg'},
  {'id': 257, 'name': 'fuboTV', 'logo_path': '/9BgaNQRMDvVlji1JBZi6tcfxpKx.jpg'},
  {'id': 546, 'name': 'WOW Presents Plus', 'logo_path': '/6dET59jNU0ADysghEjl8Unuc7Ca.jpg'},
  {'id': 1715, 'name': 'Shahid VIP', 'logo_path': '/7qZED0kLBtiV8mLRNBtW4PQCAqW.jpg'},
  {'id': 551, 'name': 'Magellan TV', 'logo_path': '/mSH24WQcRDJ2fsL5iucXqqRnSRb.jpg'},
  {'id': 1771, 'name': 'Takflix', 'logo_path': '/ed0vz5bryWIhQB5sHiuGvHKnHHn.jpg'},
  {'id': 554, 'name': 'BroadwayHD', 'logo_path': '/6IYZ4NjwPikxN7J9cfSmuyeHeMm.jpg'},
  {'id': 1825, 'name': 'HBO Max Amazon Channel', 'logo_path': '/embS4GPK7c8pjbuY2O2irV5rYch.jpg'},
  {'id': 444, 'name': 'Dekkoo', 'logo_path': '/x6nRFzF32hCzMHaVM4RHRo7lsgS.jpg'},
  {'id': 583, 'name': 'MGM+ Amazon Channel', 'logo_path': '/efu1Cqc63XrPBoreYnf2mn0Nizj.jpg'},
  {'id': 1968, 'name': 'Crunchyroll Amazon Channel', 'logo_path': '/pgjz7bzfBq4nFDu8JJDLBoUVAX8.jpg'},
  {'id': 559, 'name': 'Filmzie', 'logo_path': '/eUBxtrqO26wAJfYOZJOzhQEo3mm.jpg'},
  {'id': 567, 'name': 'True Story', 'logo_path': '/aRPDQvVcpeY07sjI6lAALMCL0ti.jpg'},
  {'id': 569, 'name': 'DocAlliance Films', 'logo_path': '/vbXJBJVv3u3YWt6ml0l0ldDblXT.jpg'},
  {'id': 2616, 'name': 'Paramount Plus Essential', 'logo_path': '/5wym1C0jAvJeGirPdgVpcW0CCuy.jpg'},
  {'id': 315, 'name': 'Hoichoi', 'logo_path': '/u7dwMceEbjxd1N3TLEUBILSK2x6.jpg'},
  {'id': 344, 'name': 'Rakuten Viki', 'logo_path': '/73uV3YooOA8gD9YQTXFj2XakZWA.jpg'},
  {'id': 300, 'name': 'Pluto TV', 'logo_path': '/dB8G41Q6tSL5NBisrIeqByfepBc.jpg'},
  {'id': 581, 'name': 'iQIYI', 'logo_path': '/c4eVkfMna2VzHzZ8N2vWXUnMrlD.jpg'},
  {'id': 1855, 'name': 'Starz Apple TV Channel', 'logo_path': '/1C5EVCWyQD798CE1DFfcm6oAbxP.jpg'},
  {'id': 1854, 'name': 'AMC Plus Apple TV Channel ', 'logo_path': '/oTQdXIqM9iewlN4MC2nhKB0gHw.jpg'},
  {'id': 1852, 'name': 'Britbox Apple TV Channel ', 'logo_path': '/bzEv2wssRqVgl12IVBfYhCIvvG.jpg'},
  {'id': 582, 'name': 'Paramount+ Amazon Channel', 'logo_path': '/hExO4PtimLIYn3kBOrzsejNv7cT.jpg'},
  {'id': 584, 'name': 'Discovery+ Amazon Channel', 'logo_path': '/lgudHqEtTOzkMWlpTjU1oUyoUSZ.jpg'},
  {'id': 1875, 'name': 'Runtime', 'logo_path': '/xm8xr6LDdY5j2gjYf1S3yqaeRbE.jpg'},
  {'id': 528, 'name': 'AMC+ Amazon Channel', 'logo_path': '/2ino0WmHA4GROB7NYKzT6PGqLcb.jpg'},
  {'id': 1860, 'name': 'Univer Video', 'logo_path': '/44E23wCM3WLsvAVRyk6fye76cZb.jpg'},
  {'id': 207, 'name': 'The Roku Channel', 'logo_path': '/wQzSN83BnWVgO7xEh0SeTVqtrFv.jpg'},
  {'id': 634, 'name': 'Starz Roku Premium Channel', 'logo_path': '/9laPF1MAiUxlqM8T98F3Gj0bhzd.jpg'},
  {'id': 635, 'name': 'AMC+ Roku Premium Channel', 'logo_path': '/gAGrSQCTAisxy2CsWbijVvJEnRo.jpg'},
  {'id': 526, 'name': 'AMC+', 'logo_path': '/ovmu6uot1XVvsemM2dDySXLiX57.jpg'},
  {'id': 636, 'name': 'MGM Plus Roku Premium Channel', 'logo_path': '/lD7HKUmXDvUya58DceiTA809Zbf.jpg'},
  {'id': 83, 'name': 'The CW', 'logo_path': '/spcwROYevucLluqZZ8Fv75UuTBt.jpg'},
];
